- Assets/SWPPT3/Scenes/Stage 2.unity
stage 2 scene 컨펌하고 light line 에셋 씬에 추가했습니다.
> fix: stage 2 scene light line fix

- Assets/SWPPT3/Prefabs/Stage1/Simple_Cube_Wood.prefab
- Assets/SWPPT3/Prefabs/Stage1/Simple_Cube_Wood.prefab.meta
- Assets/SWPPT3/Scenes/Stage 1.unity
stage1에 나무 상자가 2개 있어야 하는데 없어서
1. 무료 asset 폴더에서 swppt3 asset 폴더로 가져오고
2. stage 1 scene에 배치했습니다.
> add: two wooden boxes to stage1

- Assets/SWPPT3/Animations.meta
- Assets/SWPPT3/Animations/ButtonAnimation.meta
- Assets/SWPPT3/Animations/ButtonAnimation/Button.controller
- Assets/SWPPT3/Animations/ButtonAnimation/Button.controller.meta
- Assets/SWPPT3/Animations/ButtonAnimation/Pressed.anim
- Assets/SWPPT3/Animations/ButtonAnimation/Pressed.anim.meta
- Assets/SWPPT3/Animations/ButtonAnimation/Released.anim
- Assets/SWPPT3/Animations/ButtonAnimation/Released.anim.meta
- Assets/SWPPT3/Materials/ButtonMaterial.mat
- Assets/SWPPT3/Materials/ButtonMaterial.mat.meta
- Assets/SWPPT3/Prefabs/Stage1/Button.prefab
- Assets/SWPPT3/Prefabs/Stage1/Button.prefab.meta
- Assets/SWPPT3/VFX.meta
- Assets/SWPPT3/VFX/ButtonShaderGraph.shadergraph
- Assets/SWPPT3/VFX/ButtonShaderGraph.shadergraph.meta
버튼에 shader와 애내메이션을 넣었습니다.
눌렀을 때 버튼의 위쪽 부분이 아래로 내려가고 빛이 나고,  뗐을 때 위로 다시 올라가고 빛이 사라집니다.
Scene에는 바뀐 버튼을 반영하지 않았습니다. (원래 버튼에 해당하는 프리팹 이름이 SwitchSecret이었는데 비직관적이어서 Button이라는 이름으로 새로 만들었습니다.)
처음에 이상한 브랜치에서 작업하다가 깨닫고 옮겨왔는데 혹시 커밋 로그에 문제가 있는지 확인 부탁드립니다.
> Button animation

- Assets/SWPPT3/Animations/DoorAnimation/Shield.controller
애니메이션 파라미터 이름을 DoorClosed에서 IsClosed로 변경하였습니다.
> fix: animator parameter name to IsClosed

- Assets/SWPPT3/Animations/ButtonAnimation/Button.controller
버튼 애니메이션의 파라미터를 ButtonPressed에서 IsPressed로 변경했습니다.
> fix: changed animation parameter name to IsPressed

- Assets/SWPPT3/Animations/VentAnimation.meta
- Assets/SWPPT3/Animations/VentAnimation/Closed.anim
- Assets/SWPPT3/Animations/VentAnimation/Closed.anim.meta
- Assets/SWPPT3/Animations/VentAnimation/Closing.anim
- Assets/SWPPT3/Animations/VentAnimation/Closing.anim.meta
- Assets/SWPPT3/Animations/VentAnimation/Open.anim
- Assets/SWPPT3/Animations/VentAnimation/Open.anim.meta
- Assets/SWPPT3/Animations/VentAnimation/Opening.anim
- Assets/SWPPT3/Animations/VentAnimation/Opening.anim.meta
- Assets/SWPPT3/Animations/VentAnimation/Vent.controller
- Assets/SWPPT3/Animations/VentAnimation/Vent.controller.meta
- Assets/SWPPT3/Prefabs/Puzzle/Vent.prefab
에셋 리팩토링하면서 벤트 문의 transform에 문제가 생겨 다시 만들었습니다.
animation parameter IsClosed로 변경하였습니다.
> fix: modified doors' position and rotation in animation to make compatible with modified vent model

- Assets/SWPPT3/Animations/ItemAnimation.meta
- Assets/SWPPT3/Animations/ItemAnimation/CubeRotate.anim
- Assets/SWPPT3/Animations/ItemAnimation/CubeRotate.anim.meta
- Assets/SWPPT3/Animations/ItemAnimation/Item.controller
- Assets/SWPPT3/Animations/ItemAnimation/Item.controller.meta
- Assets/SWPPT3/Animations/ItemAnimation/SphereFloat.anim
- Assets/SWPPT3/Animations/ItemAnimation/SphereFloat.anim.meta
- Assets/SWPPT3/PhysicMaterials/ItemMaterial.physicMaterial
- Assets/SWPPT3/PhysicMaterials/ItemMaterial.physicMaterial.meta
- Assets/SWPPT3/Prefabs/Puzzle/Metal_Item.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Rubber_Item.prefab
아이템이 일정 주기로 위아래로 왕복하는 애니메이션과 아이템 내의 상자가 천천히 회전하는 애니메이션을 추가했습니다.
움직이지 않는 박스 콜라이더 적용했습니다.
> add: item animation

- Assets/SWPPT3/Animations/MagicCircleAnimation.meta
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState0.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState0.anim.meta
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState1.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState1.anim.meta
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState2.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState2.anim.meta
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState3.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState3.anim.meta
- Assets/SWPPT3/Animations/MagicCircleAnimation/MagicCircle.controller
- Assets/SWPPT3/Animations/MagicCircleAnimation/MagicCircle.controller.meta
- Assets/SWPPT3/Prefabs/Puzzle/Magic_Circle.prefab
마법진에 State를 0, 1, 2, 3으로 지정하여 완성도를 정하는 애니메이션을 만들었습니다.
추후 0, 1, 2, 3, 4로 세분화할 예정입니다.
> add: animation for magic circle

- Assets/SWPPT3/Prefabs/Puzzle/Magic_Circle.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Metal_Item.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Poison_Pool Variant.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Poison_Pool.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Round_Room_Ground_Fog.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Round_Room_Sphere_Fog.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Rubber_Cube.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Rubber_Item.prefab
마법진에 골인 판정 위해 콜라이더 추가하였습니다.
그 외에도 콜라이더가 없거나 trigger 설정 안 되어 있는 것들 수정하였습니다.
> add: collider for props

- Assets/SWPPT3/Prefabs/Puzzle/Metal_Cube.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Metal_Item.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Wood_Box.prefab
나무 상자와 금속 상자에 rigidbody 추가했습니다.
> add: rigidbody for cubes

- Assets/SWPPT3/Prefabs/Puzzle/Button_Stone.prefab
button_stone에 애니메이션이 없어서 추가했습니다.
> add: animation for button_stone

- Assets/SWPPT3/Prefabs/Puzzle/Shield.prefab
문이 한쪽 방향으로만 막히고 다른 쪽은 뚫려서 box collider로 바꿨습니다.
> fix: door collider to box collider

- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState0.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState1.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState2.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState3.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState4.anim
- Assets/SWPPT3/Animations/MagicCircleAnimation/CircleState4.anim.meta
- Assets/SWPPT3/Animations/MagicCircleAnimation/MagicCircle.controller
마법진 파츠 3->4로 바뀜에 따라 애니메이션도 4->5단계로 바꿨습니다.
> fix: magic circle animation to 5 levels

- Assets/SWPPT3/Prefabs/Puzzle/Metal_Item.prefab
item 애니메이션 버그 고친거 날라가서 다시 수정했습니다.
> fix: unpacked metal cube from metalItem

- Assets/SWPPT3/Prefabs/Puzzle/Metal_Cube.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Wood_Box.prefab
- Assets/SWPPT3/Scenes/Stage 1.unity
- Assets/SWPPT3/Scenes/Stage 2.unity
- Assets/SWPPT3/Scenes/Stage 3.unity
- Assets/SWPPT3/Scenes/Stage 4.unity
- Assets/SWPPT3/Scenes/Stage 5.unity
- Assets/SWPPT3/Scenes/Tutorial 1.unity
- Assets/SWPPT3/Scenes/Tutorial 2.unity
- Assets/SWPPT3/Scripts/Main/ScriptableObjects/CameraScript.asset
- Assets/SWPPT3/Scripts/Main/ScriptableObjects/PlayerScript.asset
test player 넣고 scriptable 등 상수 값 조절했습니다.
> fix: scene modify

- Assets/SWPPT3/Prefabs/Puzzle/Button.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Button_Stone.prefab
- Assets/SWPPT3/Prefabs/Tiles/Stairs_Platform_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_CornerCrossing_Extended.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Wall_Var3_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Round_Room.prefab
- Assets/SWPPT3/Prefabs/Walls/Stage4_Room.prefab
root 오브젝트에 box collider를 넣고, base에는 trigger랑 convex 옵션 빼서 넣었습니다.
> fix: button collider

- Assets/SWPPT3/Prefabs/Puzzle/Button_Stone.prefab
button stone collider 바꾼거 날아간거 다시 반영했습니다.
> fix: button stone collider

- Assets/SWPPT3/Animations/VentAnimation/Closed.anim
- Assets/SWPPT3/Animations/VentAnimation/Closing.anim
- Assets/SWPPT3/Animations/VentAnimation/Open.anim
- Assets/SWPPT3/Animations/VentAnimation/Opening.anim
- Assets/SWPPT3/Prefabs/Puzzle/Vent.prefab
에셋 수정하면서 벤트의 구조가 바뀌고, 상대적 컴포넌트 위치도 바뀌어서 구조 정상화와 애니메이션 수정 했습니다.
> fix: vent animation due to asset modification

- Assets/SWPPT3/Animations/MagicCircleAnimation/MagicCircle.controller
어제 guid 문제로 수정해야 한다고 했던 magicCircle animator 고쳤습니다.
> fix: magicCircle animation controlor with changed guid

- Assets/SWPPT3/Prefabs/Puzzle/Button_Stone.prefab
- Assets/SWPPT3/Prefabs/Puzzle/Electric_Wire_Set.prefab.meta
버튼에 이상하게 엄청 큰 collider가 하나 더 들어가 있어서 없앴습니다.
도데체 무슨 일이지 이게..
> fix: removed unnecessary collider form button_stone

- Assets/SWPPT3/Scenes/Stage 1.unity
- Assets/SWPPT3/Scenes/Stage 4.unity
- Assets/SWPPT3/Scenes/Stage 5.unity
- Assets/SWPPT3/Scripts/Main/ScriptableObjects/PropScript.asset
stage 4, 5에 state src/dst 연결 빠진 부분 채웠습니다.
> fix: re-link state src/dst

- Assets/SWPPT3/Scripts/Main/PlayerLogic/PlayerMover.cs
ㄴ자 형태의 지형의 옆면에 먼저 충돌할 경우 점프가 불가능한 문제가 있어 수정했습니다.
> fix: player jump condition

- Assets/SWPPT3/Scripts/Main/Prop/Vent.cs
> fix: vent now working(almost same as door)

- Assets/SWPPT3/Prefabs/ManagerObject/GameManager.prefab
- Assets/SWPPT3/Prefabs/UI/Overlay/StartScreen.prefab
- Assets/SWPPT3/Prefabs/UI/Screen/InGame.prefab
- Assets/SWPPT3/Scenes/Start.unity
- Assets/SWPPT3/Scripts/Main/Manager/GameManager.cs
- Assets/SWPPT3/Scripts/Main/StageDirector/StageManager.cs
- Assets/SWPPT3/Scripts/Main/UI/InGameScreenBehaviour.cs
- Assets/SWPPT3/Scripts/Main/UI/PlayingScreenBehavior.cs
- Assets/SWPPT3/Scripts/Main/UI/PlayingScreenBehavior.cs.meta
> chore: start load scene, radial change

- Assets/SWPPT3/Prefabs/TestPlayer2.prefab
- Assets/SWPPT3/Scenes/Stage 1.unity
- Assets/SWPPT3/Scripts/Main/PlayerLogic/Player.cs
- Assets/SWPPT3/Scripts/Main/StageDirector/Tutorial1Director.cs
- Assets/SWPPT3/Scripts/Main/UI/InGameScreenBehaviour.cs
> chore: renderer

- Assets/SWPPT3/Scenes/Stage 3.unity
- Assets/SWPPT3/Scenes/Stage 5.unity
> fix: items locked with boxes

- Assets/SWPPT3/Prefabs/UI/Playtime.prefab
- Assets/SWPPT3/Scripts/Main/StageDirector/StageManager.cs
00:00초에 00: 00으로 표시되던거 수정했습니다.
> fix: 00:00 problem solved

- Assets/SWPPT3/Scripts/Main/Utility/CameraController.cs
> fix: adjusted camera angle lower bound by 10 degree

- Assets/SWPPT3/Prefabs/TestPlayer2.prefab
- Assets/SWPPT3/Scripts/Main/ScriptableObjects/CameraScript.asset
- Assets/SWPPT3/Scripts/Main/ScriptableObjects/PlayerScript.asset
- Assets/SWPPT3/Scripts/Main/ScriptableObjects/SoftbodyScript.asset
- Assets/SWPPT3/Scripts/SoftbodyPhysics/SoftbodyGenerator.cs
> fix: changed constants

- Assets/SWPPT3/Scripts/Main/PlayerLogic/PlayerMover.cs
> fix: slime cannot push boxes with probability 1 rather than 1/2

- Assets/SWPPT3/Scripts/Main/PlayerLogic/PlayerMover.cs
머지하면서 player logic에 softbody가 사라져서 추가해줬습니다.
> fix: player logic softbody error

- Assets/SWPPT3/Prefabs/Puzzle/Magic_Circle.prefab
- Assets/SWPPT3/Prefabs/Tiles/Floor_Tile_3.prefab
- Assets/SWPPT3/Prefabs/Tiles/Floor_Tile_Half.prefab
- Assets/SWPPT3/Prefabs/Tiles/Pitfall_Left.prefab
- Assets/SWPPT3/Prefabs/Tiles/Pitfall_Middle.prefab
- Assets/SWPPT3/Prefabs/Tiles/Pitfall_Right.prefab
- Assets/SWPPT3/Prefabs/Tiles/Stairs_Platform_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Big_Window_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_CornerCrossing_Extended.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_CornerCrossing_Wall.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Custom_Border_Arched_Corner_Room_Wall.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Custom_Border_Arched_Double_Wall.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Passage_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Straight_Half_Wall.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Wall_Var1_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Wall_Var2_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Wall_Var3_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Wall_Window_Modified.prefab
- Assets/SWPPT3/Prefabs/Walls/Dungeon_Wall_Window_No_Metal.prefab
- Assets/SWPPT3/Prefabs/Walls/Round_Room.prefab
- Assets/SWPPT3/Prefabs/Walls/Stage4_Room.prefab
- Assets/SWPPT3/Prefabs/Walls/Stair_Wall.prefab
- Assets/SWPPT3/Scenes/Stage 3.unity
> fix: collider

- Assets/SWPPT3/Materials/WireMetalMaterial.mat
- Assets/SWPPT3/Materials/WireMetalMaterial.mat.meta
- Assets/SWPPT3/Prefabs/Puzzle/Electric_Wire.prefab
> fix: wire material

- Assets/SWPPT3/Scenes/Stage 1.unity
- Assets/SWPPT3/Scenes/Stage 3.unity
- Assets/SWPPT3/Scenes/Stage 5.unity
- Assets/SWPPT3/Scenes/Tutorial 1.unity
> fix: scene narrow gap narrower

- Assets/SWPPT3/Prefabs/Puzzle/Magic_Circle.prefab
> fix: magicCircle collider smaller

- Assets/SWPPT3/Prefabs/Etc/Chain_Var1.prefab
- Assets/SWPPT3/Prefabs/Etc/Chain_Var2.prefab
- Assets/SWPPT3/Prefabs/Etc/Chain_Var3.prefab
- Assets/SWPPT3/Scenes/Stage 3.unity
> fix: scene 3
